
debug: false

spring:
  datasource:
    url: jdbc:mysql://121.37.214.65:3306/demo?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: docker
    password: eGroAj8Fe5
    driver-class-name: com.mysql.cj.jdbc.Driver


logging:
  file:
    name: d:\test\test.log
  level:
    root: info

